# CREDIT: https://github.com/shren207/nextjs-docker-compose
services:
  test:
    build: .
    restart: always
    volumes:
      - ./app:/app
    working_dir: /app
    # ports:
    #   - 8080:8080
    # command: sleep infinity
    command: bash entry.sh

    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.portfolio-staging-http.rule=Host(`portfolio-staging.iamon99.com`)'
      - 'traefik.http.routers.portfolio-staging-http.entrypoints=web'
      - 'traefik.http.routers.portfolio-staging-http.middlewares=portfolio-staging-https'
      - 'traefik.http.middlewares.portfolio-staging-https.redirectscheme.scheme=https'
      - 'traefik.http.routers.portfolio-staging.rule=Host(`portfolio-staging.iamon99.com`)'
      - 'traefik.http.routers.portfolio-staging.entrypoints=websecure'
      - 'traefik.http.routers.portfolio-staging.tls.certresolver=myresolver'
      - 'traefik.http.services.portfolio-staging.loadbalancer.server.port=8080'

networks:
  default:
    external:
      name: traefik-proxy-network

volumes:
  node_modules:
